### PR TITLE
Update Mentorship page

### PR DESCRIPTION
**Pull request by peterbsmith2**

### CODE REVIEW

**Comment by annalenadavis** [comment]
I think this is really close! I like the look of the tailwindUI testimonials. But I'm not liking two columns on mobile. It's just too tight. But if we keep two columns, we need to adjust the styles for the footers in the testimonials so the names and images fit properly.

Also some typos:
- Typo in first sentence: "The program pairs professional **egineers**..."
- Not in this PR- but I just noticed a typo in the nav bar Programs menu too, under Events, it says "**virutally**"

**Comment by peterbsmith2** [comment]
on this PR:

```
Nathan E 
Mentor, January 2021 
```
=> 
```
Nathan Evans 
Mentor, January 2021 
```

on the site footer:

```
Coalition of Digital Engagement in Syracuse is a registered 501c3
```

=> 

```
Coalition of Digital Engagement in Syracuse, Inc. is a registered 501(c)3
```

on the site homepage:

```
Coalition of Digital Engagements Syracuse
```

=>

```
Coalition of Digital Engagement Syracuse
```

on the site meta:

Screen Shot 2021-02-11 at 8 50 01 AM

=>

```
Coalition of Digital Engagement in Syracuse
```


on the site <title>:

```
CODESyracuse | Coalition of Digital Engagements, Syracuse
```

=>

```
CODESyracuse | Coalition of Digital Engagement in Syracuse
```

**Comment by peterbsmith2** [comment]
### on the site donate button a light gray 1px border or box shadow is visible, related to a class `.ml-8`:

Screen Shot 2021-02-11 at 8 55 14 AM


Screen Shot 2021-02-11 at 8 54 42 AM

**Comment by vormwald** [comment]
@peterbsmith2 / @annalenadavis thanks for catching my typos! 

The button has a box shadow on purpose... tailwind UI buttons tend to have them to make them stand out. Would you rather remove that from the Donate button? @peterbsmith2 ?

**Pull request merged**
